# Generated by Django 3.0.8 on 2020-07-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_where', models.CharField(max_length=200)),
                ('to_where', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('freight_by_owner', models.FloatField()),
                ('freight_by_customer', models.FloatField()),
                ('customer_acceptance', models.CharField(max_length=7)),
                ('owner_acceptance', models.CharField(max_length=7)),
            ],
        ),
    ]
