# Generated by Django 3.0.8 on 2020-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_acceptance',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='freight_by_owner',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner_acceptance',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
