# Generated by Django 3.0.8 on 2020-07-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0003_auto_20200705_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_acceptance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='freight_by_customer',
        ),
    ]
