# Generated by Django 3.0.8 on 2020-07-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0004_auto_20200705_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner_acceptance',
            new_name='acceptance',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='freight_by_owner',
            new_name='freight',
        ),
    ]
