# Generated by Django 3.0.8 on 2020-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0005_auto_20200705_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='acceptance',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
