# Generated by Django 3.0.8 on 2020-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0006_auto_20200705_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='acceptance',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
